--------------------------------------------------------
-- Archivo creado  - viernes-junio-10-2022   
--------------------------------------------------------
REM INSERTING into PF_AGO.MEMBERS
SET DEFINE OFF;
Insert into PF_AGO.MEMBERS (ID_MEMBER,NAME_MEMBER,SHORT_NAME_MEMBER,DNI_MEMBER,EMAIL_MEMBER,PHONE_MEMBER,ID_PRO_CAT,PHOTO_MEMBER,RESEARCH_ID_MEMBER,SCOPUS_ID_MEMBER,ORC_ID_MEMBER,TRAJECTORY_MEMBER,UPDATE_ADMIN,UPDATE_DATE,ACTIVE) values ('1','Moreno García, Virginia','VirginiaMoreno',null,'virginia.moreno@icmse.csic.es',null,'5','1member1.jpg',null,null,'0000-0002-9132-0995','VIRGINIA MORENO has a PhD in Analytical Chemistry from the Regional Institute for Research in Applied Sciences (IRICA) at the University of Castilla-La Mancha (UCLM), Spain, since 2014. He received his Bachelor''s degree in Chemistry in 2013 and his Master''s degree in 2014 from the UCLM. He obtained an official research grant from the JCCM of Spain for his doctoral thesis in 2014. In addition, his thesis focused on the development and validation of new analytical processes incorporating nanomaterials for food waste control. He is currently working on the synthesis of new materials for the storage of concentrated solar energy using Calcium-Looping at the Institute of Materials Science (Seville)','Admin',to_date('10/06/22','DD/MM/RR'),'1');
Insert into PF_AGO.MEMBERS (ID_MEMBER,NAME_MEMBER,SHORT_NAME_MEMBER,DNI_MEMBER,EMAIL_MEMBER,PHONE_MEMBER,ID_PRO_CAT,PHOTO_MEMBER,RESEARCH_ID_MEMBER,SCOPUS_ID_MEMBER,ORC_ID_MEMBER,TRAJECTORY_MEMBER,UPDATE_ADMIN,UPDATE_DATE,ACTIVE) values ('2','Gil González, Eva','Eva Gil-González',null,'eva.gil@icmse.csic.es',null,'5','2member2.jpg',null,null,'0000-0001-8464-8653',null,'Admin',to_date('10/06/22','DD/MM/RR'),'1');
Insert into PF_AGO.MEMBERS (ID_MEMBER,NAME_MEMBER,SHORT_NAME_MEMBER,DNI_MEMBER,EMAIL_MEMBER,PHONE_MEMBER,ID_PRO_CAT,PHOTO_MEMBER,RESEARCH_ID_MEMBER,SCOPUS_ID_MEMBER,ORC_ID_MEMBER,TRAJECTORY_MEMBER,UPDATE_ADMIN,UPDATE_DATE,ACTIVE) values ('3','Alcalá González, María Dolores','Alcalá, M.D.',null,'mdalcala@us.es','954 48 95 41','3','3member3.png',null,null,'0000-0002-9800-2439',null,'Admin',to_date('10/06/22','DD/MM/RR'),'1');
Insert into PF_AGO.MEMBERS (ID_MEMBER,NAME_MEMBER,SHORT_NAME_MEMBER,DNI_MEMBER,EMAIL_MEMBER,PHONE_MEMBER,ID_PRO_CAT,PHOTO_MEMBER,RESEARCH_ID_MEMBER,SCOPUS_ID_MEMBER,ORC_ID_MEMBER,TRAJECTORY_MEMBER,UPDATE_ADMIN,UPDATE_DATE,ACTIVE) values ('4','Gotor Martínez, Francisco José','Francisco J. Gotor',null,'francisco.gotor@icmse.csic.es','954 48 95 40','2','4member4.png',null,null,'0000-0002-8943-5291',null,'Admin',to_date('10/06/22','DD/MM/RR'),'1');
Insert into PF_AGO.MEMBERS (ID_MEMBER,NAME_MEMBER,SHORT_NAME_MEMBER,DNI_MEMBER,EMAIL_MEMBER,PHONE_MEMBER,ID_PRO_CAT,PHOTO_MEMBER,RESEARCH_ID_MEMBER,SCOPUS_ID_MEMBER,ORC_ID_MEMBER,TRAJECTORY_MEMBER,UPDATE_ADMIN,UPDATE_DATE,ACTIVE) values ('5','Real Pérez, Concepción','Real, C.',null,'creal@icmse.csic.es','954 48 95 49','2','5member5.png',null,null,'0000-0002-3463-3629',null,'Admin',to_date('10/06/22','DD/MM/RR'),'1');
Insert into PF_AGO.MEMBERS (ID_MEMBER,NAME_MEMBER,SHORT_NAME_MEMBER,DNI_MEMBER,EMAIL_MEMBER,PHONE_MEMBER,ID_PRO_CAT,PHOTO_MEMBER,RESEARCH_ID_MEMBER,SCOPUS_ID_MEMBER,ORC_ID_MEMBER,TRAJECTORY_MEMBER,UPDATE_ADMIN,UPDATE_DATE,ACTIVE) values ('6','Gómez García, Diego','Diego Gómez-García',null,'dgomez@us.es','954 13 92 16','1','6member6.jpeg',null,null,'0000-0002-5639-4796',null,'Admin',to_date('10/06/22','DD/MM/RR'),'1');
Insert into PF_AGO.MEMBERS (ID_MEMBER,NAME_MEMBER,SHORT_NAME_MEMBER,DNI_MEMBER,EMAIL_MEMBER,PHONE_MEMBER,ID_PRO_CAT,PHOTO_MEMBER,RESEARCH_ID_MEMBER,SCOPUS_ID_MEMBER,ORC_ID_MEMBER,TRAJECTORY_MEMBER,UPDATE_ADMIN,UPDATE_DATE,ACTIVE) values ('7','Isabel Romero Hermida','María Isabel Romero-Hermida',null,'isabel@us.es',null,'4','7member7.jpeg','E-6344-2019','56480722000','0000-0003-3708-0959','Licenciada en Ciencias Físicas por la Universidad de Sevilla. Máster en “Técnología Química y ambiental” por la Universidad de Sevilla. Actualmente realiza la Tesis Doctoral en el programa de Doctorado de Ciencia y Tecnología de Nuevo Materiales, en la línea de investigación Materiales de Diseño para la Energía y el Medioambiente. Experiencia en caracterización de propiedades físico-químicas, microestructura y composición de productos y subproductos cristalinos sintetizados, síntesis por métodos químicos de nuevos materiales y desarrollo de materiales secuestrantes de CO2.','Admin',to_date('10/06/22','DD/MM/RR'),'1');
