--------------------------------------------------------
-- Archivo creado  - viernes-junio-10-2022   
--------------------------------------------------------
REM INSERTING into PF_AGO.NEWS
SET DEFINE OFF;
Insert into PF_AGO.NEWS (ID_NEWS,TITLE_NEWS,IMAGE_NEWS,ABSTRACT_NEWS,CONTENT_NEWS,UPDATE_ADMIN,UPDATE_DATE,ACTIVE) values ('9','Publicados los nombres de los ganadores de los Premios Nobel 2021','9new9.jpg',null,'Hace unos días se otorgaron los Premio Nobel 2021 y de entre las dos categorías de Física y Química respectivamente, ha habido varios premiados.

Los ganadores del Premio Nobel de Física han sido Syukuro Manabe, Klaus Hasselmann y Giorgio Parisi.Éstos han sido galardonados con este enorme reconocimiento por dar con nuevos métodos para describir y predecir en los sistemas complejos, el desorden y la aleatoriedad a largo plazo.

Syukuro Manabe consiguió demostrar cómo un incremento en los niveles de dióxido de carbono en la atmósfera conlleva un aumento de las temperaturas en la superficie terrestre. El científico japonés ya lideró el desarrollo de modelos físicos del clima de la Tierra en la década de los 60, además de ser la primera persona en explorar la interacción entre el equilibrio de la radiación y el transporte vertical de masas de aire. Por todo ello, sus esfuerzos a lo largo de sus 90 años de vida han sentado las bases para el desarrollo de los modelos climáticos que se manejan en la actualidad, valiéndole el máximo galardón el Nobel, un premio que comparte con Klaus Hasselmann. El investigador alemán, creó un modelo que enlaza el clima y el tiempo atmosférico para explicar por qué los modelos climáticos –pensados a largo plazo– pueden ser fiables a pesar de que el tiempo atmosférico –donde entra en juego el corto plazo– sea caótico y cambiante. Además, también desarrolló modelos para identificar las huellas que dejan los fenómenos naturales y la actividad humana en el clima.

En base a las investigaciones de Hasselmann y al poder conocer esas señales específicas, sus métodos han sido utilizados para demostrar que el aumento de la temperatura en la atmósfera se debe a las emisiones humanas de dióxido de carbono. Gracias a las investigaciones de estos científicos sabemos cómo funciona el cambio climático y cuál es la implicación del ser humano en este proceso.

Por su parte, el tercer galardonado en Física, Giorgio Parisi descubrió en la década de los 80 los patrones ocultos en los materiales complejos desordenados, unas contribuciones que se sitúan entre las más importantes del campo de la teoría de los sistemas complejos.Sus investigaciones han hecho posible el entendimiento y la descripción de materiales y fenómenos aparentemente aleatorios en áreas como la física, las matemáticas, la biología, la neurociencia y el machine learning.','Admin',to_date('10/06/22','DD/MM/RR'),'1');
Insert into PF_AGO.NEWS (ID_NEWS,TITLE_NEWS,IMAGE_NEWS,ABSTRACT_NEWS,CONTENT_NEWS,UPDATE_ADMIN,UPDATE_DATE,ACTIVE) values ('8','Ana Borrás gana el Premio Losada Villasante','8new8.jpg',null,'La investigadora del Instituto de Ciencia de los Materiales de Sevilla y jefa del Grupo de Nanotecnologías en Superficies y Plasma, Ana Borrás, ha obtenido el Premio Losada Villasante a la Investigación en Innovación por su trabajo sobre "Análisis sobre materiales avanzados para la captación de energía ambiental". Su investigación parte del concepto de “multisource micro-scale energy harvesting” o recolección de energía ambiental o residual y es el objetido del trabajo en el que se encuentra actualmente su grupo, el Proyecto 3DScavengers. 

Ana Borrás nos explica que las energías cinética, térmica y solar están de forma omnipresentes en nuestro entorno bajo diversas formas como vibraciones, cambios y gradientes de temperatura, iluminación solar y artificial, etc. pero su conversión mediante dispositivos de pequeña escala está limitada debido a la naturaleza intermitente y aleatoria de estas fuentes. Como respuesta a estas limitaciones, la comunidad científica ha comenzado a plantear muy recientemente el desarrollo de sistemas capaces de recolectar de varias fuentes simultáneamente o de forma secuencial pero usando un único dispositivo, nanogeneradores híbridos o multifuente.

Estos nanogeneradores trabajan bajo dos principios: 1) combinar diferentes recolectores de una sola fuente en un dispositivo, o 2) usar materiales multifuncionales capaces de convertir simultáneamente varias fuentes de energía en electricidad. En 1), la eficiencia por unidad de volumen puede disminuir en comparación con los recolectores individuales; en 2), aún se requiren grandes avances para optimizar la funcionalidades y fabricación sostenible a gran escala de materiales multifuncionales que se presentan como candidatos potenciales, como algunos semiconductores piezoeléctricos, óxidos y poliméros ferroeléctricos y perovskitas híbridas.','Admin',to_date('10/06/22','DD/MM/RR'),'1');
Insert into PF_AGO.NEWS (ID_NEWS,TITLE_NEWS,IMAGE_NEWS,ABSTRACT_NEWS,CONTENT_NEWS,UPDATE_ADMIN,UPDATE_DATE,ACTIVE) values ('7','Vuelve el concurso de nanorelatos del Festival de 10alamenos9','7new7.jpg',null,'Con motivo de la vuelta un año más, del Festival de 10alamenos9, se abre la participación para el concurso de nanorelatos con el objetivo de seguir fomentando en la comunidad educativa el interés por el mundo a escala nanométrica (nanomundo), que siendo tan diminuto, es muy diverso e interesante.

Este concurso va dirigido a alumnos y alumnas que estén realizando sus estudios en centros públicos, concertados o privados ubicados en Andalucía, y que tengan entre 14 y 17 años de edad a fecha 31/12/2021.

Para poder participar, os dejamos las bases del concurso:

BASES

Podrán participar en este concurso alumnos que estén realizando sus estudios en centros públicos, concertados o privados ubicados en Andalucía:

- Categoría A: participantes con 14 o 15 años a fecha de 31/12/2021.
- Categoría B: participantes con 16 o 17 años a fecha de 31/12/2021.
Cada participante podrá presentar, bajo pseudónimo, una sola obra con la que no haya participado en ningún otro concurso.','Admin',to_date('10/06/22','DD/MM/RR'),'1');
Insert into PF_AGO.NEWS (ID_NEWS,TITLE_NEWS,IMAGE_NEWS,ABSTRACT_NEWS,CONTENT_NEWS,UPDATE_ADMIN,UPDATE_DATE,ACTIVE) values ('6','Asunción Fernández recibe la Medalla de Sevilla','6new6.jpg',null,'La Profesora Asunción es doctora en Química y licenciada en Física. En 1983 empezó su postdoc en la Universidad de Sevilla y en 1987 se unió al ICMS como colaboradora científica, donde diez años después se convirtió en investigadora para posteriormente, en el 2002 se convirtió en Profesora de Investigación del CSIC. Ha liderado el Grupo de Investigación "Nanostructured Materials and Microstructure-NanoMatMicro" desde 1991 y es la investigadora principal del laboratorio de microscopía electrónica del ICMS desde 1996. Asunción fue directora del propio instituto durante 8 años. Entre otras muchas condecoraciones internacionales, en 2014 obtuvo la condecoración de "Academic Guest" en los labratorios EMPA en Suiza.

Sus investigaciones han estado principalmente enfocadas en el estudio físico-químico de los nanomateriales, en especial en la sintesis de nanopartículas y láminas finas nanoestrucuradas, además de aplicar técnicas de caracterización microestrucural para el estudio de materiales en escala nanométrica. En particular, nuestra investigadora ha trabajado en los campos de fotocatálisis con semiconductores, Química de superficies, almacenamiento de hidrógeno y deposición por pulverización catódica de magnetron de láminas y recubrimientos.

En el presente, Asunción Fernández está investigando en la fabricación innovadora de láminas finas nanoestructuradas mediante deposición por pulverización asistida por plasmas de helio y otros gases ligeros. La fabricación de láminas de nanocompuestos gas-sólido y sus aplicaciones en el estudio de reacciones nucleares, campo en el que es pionera.','Admin',to_date('10/06/22','DD/MM/RR'),'1');
Insert into PF_AGO.NEWS (ID_NEWS,TITLE_NEWS,IMAGE_NEWS,ABSTRACT_NEWS,CONTENT_NEWS,UPDATE_ADMIN,UPDATE_DATE,ACTIVE) values ('5','Tras un año de espera, vuelven los Premios cicCartuja Ebro Foods','5new5.jpg',null,'Juan José Moreno (2019) por su investigación que permitirá diseñar mejores catalizadores basados en el ligando Cp y otros análogos, así como descubrir transformaciones todavía inéditas, y José Luis Santos (2020) por su estudio para el aprovechamiento de biomasa residual con fines energéticos, han sido los ganadores del premio cicCartuja Ebro Foods 2019 y 2020. Una edición que alcanza la décima y undécima edición respectivamente. Este galardón reconoce el trabajo realizado por jóvenes investigadores menores de 31 años que previamente han publicado artículos científicos en revistas de gran prestigio internacional relacionadas con áreas como la Química, la Bioquímica o la Ciencia de Materiales.


En la edición del 2019, el primer accésit ha sido concedido a Valle Ojeda, del Instituto de Bioquímica Vegetal y Fotosíntesis (IBVF), por sus estudios sobre la especie modelo Arabidposis thaliana, que sientan las bases para estrategias biotecnológicas dirigidas a aumentar la productividad vegetal y disminuir los niveles de CO2 en la atmósfera. Recogió su premio Juan Manuel Pérez Ruíz, ya que Valle está actualmente haciendo una estancia en la Universidad de Berkeley (California). En el segundo accésit, concedido a Sara Navarro del Instituto de Ciencia de los Materiales de Sevilla (ICMS), se premia el diseño de nuevos catalizadores activos y selectivos para la reacción de WGS (generación de H2 como fuente de energía) capaces de operar en las condiciones de trabajo reales de una celda de combustible. Recogió su premio Svetlana Ivanova, dado que Sara está en la Universidad de Lille, en Francia, haciendo una estancia post-doctoral con el CNRS (Centre National de la Recherche Scientifique), que es el equivalente al CSIC en España.

Respecto a la edición 2020, el primer accésit ha sido concedido a Macarena González Alférez, del Instituto de Investigaciones Químicas (IIQ) por sus estudios sobre ligandos ciclopentadienilos (Cp) en la química organometálica y catálisis homogénea (en particular, el pentametilciclopentadienilo). El segundo accésit, por su parte, ha sido otorgado a Ester López (ICMS) por su trabajo sobre la posibilidad que ofrece la técnica de magnetron sputtering para la fabricación de electrodos con distinta microestructura, estado químico o espesor de catalizadores de níquel, aplicados a la generación de H2.','Admin',to_date('10/06/22','DD/MM/RR'),'1');
Insert into PF_AGO.NEWS (ID_NEWS,TITLE_NEWS,IMAGE_NEWS,ABSTRACT_NEWS,CONTENT_NEWS,UPDATE_ADMIN,UPDATE_DATE,ACTIVE) values ('4','Arranca la VII del 11F, el Día de la Mujer y la Niña en la Ciencia','4new4.jpg',null,'El 11 de febrero volvemos a celebrar el Día Internacional de la mujer y la niña en la ciencia, una iniciativa a la que nos sumamos un año más para eliminar los estereotipos de género dentro del ámbito de la ciencia y la tecnología (STEM), para ayudar a fomentar las vocaciones científicas y tecnológicas en niñas y adolescentes y dar mayor visibilidad al trabajo de las científicas. Pero lo más importante, para conocer las causas de la brecha de género y promover prácticas que favorezcan la igualdad de género en el ámbito científico.

Este 2022 el 11F celebra su séptima edición y para este evento, se celebrarán actividades tanto en formato virtual como presencial. Una vez más, científicas, investigadoras y divulgadoras de todas partes, comparten sus conocimientos para transmitir su pasión por la ciencia. Con motivo de la celebración de este acontecimiento tan especial, a lo largo de estos días nuestras investigadoras del IIQ, ICMS e IBVF, volverán a acercar la ciencia a todos los públicos.','Admin',to_date('10/06/22','DD/MM/RR'),'1');
Insert into PF_AGO.NEWS (ID_NEWS,TITLE_NEWS,IMAGE_NEWS,ABSTRACT_NEWS,CONTENT_NEWS,UPDATE_ADMIN,UPDATE_DATE,ACTIVE) values ('3','Tomás Ramírez Reina premiado por su labor científica internacional','3new3.png',null,'La Federación Iberoamericana de Sociedades de Catálisis (FISOCAT), que reúne las Sociedades Nacionales de Catálisis de 11 países iberoamericanos (Argentina, Brasil, Chile, Colombia, Cuba, España, México, Perú, Portugal, Uruguay y Venezuela), ha otorgado el Premio a la Trayectoria Científica de Excelencia FISOCAT 2022 Junior, al Dr. Tomás Ramírez Reina del Instituto de Ciencias de Materiales de Sevilla. Este premio se concede bianualmente desde 2006 y distingue en su categoría junior a investigadores menores de 40 años de amplia y reconocida labor científica internacional.  La entrega del premio se hará en septiembre y tendrá lugar en el marco del XXVIII Congreso Iberoamericano de Catálisis en Brasil donde Tomás impartirá una conferencia plenaria. ','Admin',to_date('10/06/22','DD/MM/RR'),'1');
Insert into PF_AGO.NEWS (ID_NEWS,TITLE_NEWS,IMAGE_NEWS,ABSTRACT_NEWS,CONTENT_NEWS,UPDATE_ADMIN,UPDATE_DATE,ACTIVE) values ('2','Alberto Jiménez Solano, galardonado con el premio Jóvenes Investigadores','2new2.jpeg',null,'El investigador Alberto Jiménez Solano es doctor en Física por la Universidad de Sevilla y actualmente trabaja en el Instituto Max Planck de Munich.

Su labor se centra en el estudio de la nanofotónica y de los nuevos sensores. Durante su estancia en el Instituto de Ciencia de los Materiales de Sevilla, realizó su tesis doctoral de la mano del grupo MOM (Materiales Ópticos Multifuncionales), bajo la supervisión del Prof. Hernán Míguez y el Dr. Juan F. Galisteo. Trabajo con el que ganó el segundo accésit del premio a la mejor tesis doctoral presentada en 2017, concedido por el Grupo especializado de Nanociencia y materiales moleculares (NanoMatMol) de la Real Sociedad Española de Química (RSEQ) y de la Real Sociedad Española de Física (RSEF).

A partir de entonces, su carrera investigadora en el estudio de las interacciones entre la materia y la luz, ha ido ascendiendo y eso le ha otorgado uno de los Premios Jóvenes Investigadores que otorga la Real Maestranza de Caballería de Sevilla, unos galardones, que junto con la Real Academia Sevillana de Ciencias, llega a su trigésimo primera edición desde que en 1989 se inauguraran.

Han pasado tres años desde la última edición, que debido a la crisis sanitaria no ha podido celebrarse antes, por lo que se trata de la convocatoria correspondiente a 2019. A esta edición se presentaron un total de 50 propuestas de las que 20 correspondían a Biología, 5 a física y otras 5 a Matemáticas, 8 a Química y 15 a Tecnología. 

La secretaria del jurado, Carmen Hermosín, ha destacado en la ceremonia de entrega, la dificultad de elección debido a la gran calidad que presentaban todos los trabajos. Cada premio de los que se ha dado, está dotado con 6.000 euros y va dirigido a jóvenes investigadores con menos de 35 años. Dos de ellos corresponden a la Real Maestranza (de los cuales uno se ha llevado Alberto Jiménez) y otro al de la Real Academia Sevillana de Ciencias. 

Le auguramos un brillante futuro a este investigador, que desde sus comienzos en el ICMS ya mostraba que iba a ser imparable.','Admin',to_date('10/06/22','DD/MM/RR'),'1');
Insert into PF_AGO.NEWS (ID_NEWS,TITLE_NEWS,IMAGE_NEWS,ABSTRACT_NEWS,CONTENT_NEWS,UPDATE_ADMIN,UPDATE_DATE,ACTIVE) values ('1','Mercedes Nieves Morión ha obtenido el Premio Extraordinario de Doctorado','1new1.jpg',null,'Mercedes Nieves Morión, actual investigadora postdoctoral del Instituto de Bioquímica Vegetal y Fotosíntesis (IBVF), ha obtenido el Premio Extraordinario de Doctorado en la categoría de Bioquímica y Biología Molecular por su tesis defendida en el curso académico 2017-2018.

Mercedes realizó su tesis doctoral en el grupo de investigación Biología del Desarrollo en Cianobacterias del IBVF gracias a la obtención de una beca/contrato de Formación del Profesorado Universitario (FPU), bajo la dirección del Dr. Enrique Flores y tutorización del Dr. José María Romero.
En su tesis, Mercedes centró su investigación en el campo de las cianobacterias, organismos procariotas fotosintéticos de gran importancia en la evolución de la vida en la Tierra debido a su papel en la oxigenación de nuestro planeta y al ser las precursoras de los cloroplastos de plantas y algas. En concreto, sus estudios se centraron en el uso de técnicas microbiológigas, genéticas y moleculares aplicadas a la cianobacteria filamentosa Anabaena sp., que es un modelo para el estudio de la fijación de nitrógeno, la diferenciación celular y la multicelularidad en el mundo bacteriano. Entre los resultados de su investigación destacan la identificación de un mecanismo de difusión en la comunicación intercelular en cianobacterias filamentosas, la caracterización de transportadores de glucósidos relacionados con la asimilación de azúcares que indicaron el carácter mixotrófico de esta cianobacteria modelo, y la influencia de dichos transportadores sobre las conexiones septales entre células (“septal junctions”) para el correcto funcionamiento de la comunicación intercelular. Los resultados obtenidos en la tesis fueron publicados en revistas científicas de primera línea en el ámbito de la Microbiología y presentados en congresos de carácter nacional e internacional. Además, Mercedes desempeñó tareas docentes en la Universidad de Sevilla (Departamento de Bioquímica Vegetal y Biología Molecular) y realizó una estancia en la Queen Mary University of London (School of Biological and Chemical Sciences), obteniendo así el doctorado con mención internacional. ','Admin',to_date('10/06/22','DD/MM/RR'),'1');
