--------------------------------------------------------
-- Archivo creado  - viernes-junio-10-2022   
--------------------------------------------------------
REM INSERTING into PF_AGO.PROJECTS
SET DEFINE OFF;
Insert into PF_AGO.PROJECTS (ID_PROJECT,TITLE_PROJECT,IMAGE_PROJECT,DESCRIPTION_PROJECT,UPDATE_ADMIN,UPDATE_DATE,ACTIVE) values ('1','FreeDot- Optimized Photonic Design of Ligand-Free Perovskite Quantum Dot based Optoelectronic Devices
Ministerio de Ciencia e Innovación  (Nº expediente: PID2020-116593RB-I00)','1project1.jpg','The motivation of the FreeDot project is three-fold. First, to propose solutions to the specific drawbacks hindering further development of perovskite optoelectronic technology (instability, durability, environmental sensitivity, etc.) by developing nanostructured solar cells and LEDs based on novel porous scaffolds that permit the synthesis of ligand-free nanocrystal assemblies, which show dot-to-dot charge transport while, simultaneously, minimizing their exposure to degrading environments. Second, to prove that improved power conversion efficiency, in the case of solar cells, and enhanced outcoupling and control over the spectral and directional properties of the emitted light, in the case of LEDs, are achievable through the optimization of the optical design also for quantum dot based devices. Finally, the synthesis of ligand-free nanocrystals opens the possibility to study fundamental photophysical properties of quantum dots, which are hindered by the presence of organic cappings in colloidal nanocrystals.','Admin',to_date('10/06/22','DD/MM/RR'),'1');
Insert into PF_AGO.PROJECTS (ID_PROJECT,TITLE_PROJECT,IMAGE_PROJECT,DESCRIPTION_PROJECT,UPDATE_ADMIN,UPDATE_DATE,ACTIVE) values ('2','PERSEPHONe – PERovskite SEmiconductors for PHOtoNics
Research Executive Agency – European Union','2project2.jpg','Funded by the Marie Sk?odowska-Curie programme, PERSEPHONe is a coordinated training network that aims to equip young researchers with new skills and knowledge regarding the development of a novel photonics technological platform based on metal-halide perovskite semiconductors. These materials present unrivalled optoelectronic properties and can be engineered to achieve a large set of desirable functionalities which may change the roadmap of currently established photonic technologies. They also show great promise for their integration with silicon photonics and silicon-oxynitride-based photonics. The programme will expose 14 early-stage researchers to a wide spectrum of research activities including material synthesis, photonic (and optoelectronic) device and integrated circuit fabrication, characterisation, modelling, upscaling and manufacturing. PERSEPHONe will lay the foundation for a novel photonic technology, strengthening Europe’s position in the field.','Admin',to_date('10/06/22','DD/MM/RR'),'1');
Insert into PF_AGO.PROJECTS (ID_PROJECT,TITLE_PROJECT,IMAGE_PROJECT,DESCRIPTION_PROJECT,UPDATE_ADMIN,UPDATE_DATE,ACTIVE) values ('3','NANOPHOM – NANOPHOSPHOR-BASED PHOTONIC MATERIALS FOR NEXT GENERATION LIGHT-EMITTING DEVICES 
European Research Council Executive Agency','3project3.jpg','Energy-efficient and environmentally friendly light sources are an essential part of the global strategy to reduce the worldwide electricity consumption. Light-emitting diodes (LEDs) emerge as a key alternative to conventional lighting, due to their high power-conversion efficiency, long lifetime, fast switching, robustness, and compact size. Nonetheless, their implementation in the consumer electronic industry is hampered by the limited control over brightness, colour quality and directionality of LED emission that conventional optical elements relying on geometrical optics provide. NANOPHOM seeks to explore new ways of controlling the emission characteristics of nanophosphors, surpassing the limits imposed by conventional optics, through the use of nanophotonics. The development of reliable and scalable nanophosphor-based photonic materials will allow ultimate spectral and angular control over the light emission properties, addressing the critical shortcomings of current LEDs. The new optical design of these devices will be based on multilayers, surface textures and nano-scatterers of controlled composition, size and shape, to attain large-area materials possessing photonic properties that will enable a precise management of the visible radiation.','Admin',to_date('10/06/22','DD/MM/RR'),'1');
