
DROP TABLE NEWS;
DROP TABLE LINKS;
DROP TABLE AUTHORS_PUBLICATIONS;
DROP TABLE PUBLICATIONS;
DROP TABLE MEMBERS;
DROP TABLE FACILITIES;
DROP TABLE TECHNICAL_CATEGORIES;
DROP TABLE PROFESSIONAL_CATEGORIES;
DROP TABLE THESIS;
DROP TABLE PROJECTS;
DROP TABLE ADMINS;

DROP SEQUENCE SEQ_NEWS;
DROP SEQUENCE SEQ_LINKS;
DROP SEQUENCE SEQ_AUTHORS_PUBLICATIONS;
DROP SEQUENCE SEQ_PUBLICATIONS;
DROP SEQUENCE SEQ_PROJECTS;
DROP SEQUENCE SEQ_THESIS;
DROP SEQUENCE SEQ_PROFESSIONAL_CATEGORIES;
DROP SEQUENCE SEQ_TECHNICAL_CATEGORIES;
DROP SEQUENCE SEQ_FACILITIES;
DROP SEQUENCE SEQ_MEMBERS;
DROP SEQUENCE SEQ_ADMINS;